mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.zjy.dto
pagehelper:
  helperDialect: mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/toolsitemvc4j?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
logging:
  level:
    com:
      zjy:
        daos: debug
info:
  app:
    name: spring-boot-actuator
    version: 1.0.0
    test: test
management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
    shutdown:
      enabled: true
#management.endpoints.web.base-path=/monitor